/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "top"
include(":address")
include(":tonlib")
include(":mnemonic")
include(":utils")
include(":cell")
include(":bitstring")
