@startuml
class org.ton.java.smartcontract.integrationtests.TestHighloadWalletV3 {
+ void testSinglePayloadTransfer()
+ void testBulkPayloadTransfer3DifferentRecipients()
+ void testBulkPayloadTransfer200DifferentRecipients()
+ void testHighloadQueryId()
~ Cell createNMessages(int,HighloadWalletV3,long)
- Cell createMessageToSendForDeploy(Address,double,long,TweetNaclFast.Signature.KeyPair)
- Cell createMessageToSend(Address,double,long,TweetNaclFast.Signature.KeyPair)
- Cell createMessageBulkToSend(Address,BigInteger,Cell,long,TweetNaclFast.Signature.KeyPair,HighloadWalletV3)
}



org.ton.java.smartcontract.integrationtests.CommonTest <|-- org.ton.java.smartcontract.integrationtests.TestHighloadWalletV3
@enduml