@startuml
class ExternalMessageOutInfoRelaxed {
~ long magic
~ MsgAddress srcAddr
~ MsgAddress dstAddr
~ BigInteger createdLt
~ long createdAt
- String getMagic()
+ Cell toCell()
+ {static} ExternalMessageOutInfoRelaxed deserialize(CellSlice)
}




CommonMsgInfoRelaxed <|.. ExternalMessageOutInfoRelaxed
@enduml