@startuml
class org.ton.java.tlb.types.ExternalMessageOutInfoRelaxed {
~ long magic
~ MsgAddress srcAddr
~ MsgAddress dstAddr
~ BigInteger createdLt
~ long createdAt
- String getMagic()
+ Cell toCell()
+ {static} ExternalMessageOutInfoRelaxed deserialize(CellSlice)
}




org.ton.java.tlb.types.CommonMsgInfoRelaxed <|.. org.ton.java.tlb.types.ExternalMessageOutInfoRelaxed
@enduml