/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("io.github.neodix42.java-conventions")
}

dependencies {
    compileOnly("org.bouncycastle:bcprov-jdk15on:1.70")
    annotationProcessor("org.projectlombok:lombok:1.18.24")
    compileOnly("org.projectlombok:lombok:1.18.24")
    testImplementation("junit:junit:4.13.2")
    testImplementation("org.assertj:assertj-core:3.23.1")
}

description = "TON Java Mnemonic"
